

export const jobSections = [
    {name:'allroles', label: 'All Roles'},
    {name:'development', label: 'Development'},
    {name:'uiuxdesigning', label: 'ui/ux designing'},
    {name:'qatesting', label: 'qa / testing'},
]



export const jobOpenings = [
    {
        id: 'NOWIT-JO-001',
        section: 'development',
        role: 'Software Developer',
        detailedRole: 'Packaged Application Development Team Lead',
        location: 'New York, USA',
        type: 'Full-time',
        experience: '2+ years',
        description: 'Bachelor’s degree in Computer Science, Engineering, or equivalent experience. Strong understanding of programming fundamentals and problem-solving skills.',
        requirements: ['BS in Computer Science', 'JavaScript proficiency', 'Agile experience'],
        skills: ['JavaScript', 'Python', 'Java'],
        projectRole: 'Software Developer',
        projectDescription: 'Building and maintaining high-quality applications.',
        educationalQualifications: 'Bachelor’s degree in CS',
        benefits: ['Health Insurance', '401(k) Matching', 'Remote Options'],
        summary: 'Opportunity for a forward-thinking Developer.',
        postedDate: '2024-06-01',
    },
    {
        id: 'NOWIT-JO-002',
        section: 'development',
        role: 'Frontend Engineer',
        detailedRole: 'Senior React Developer',
        location: 'Austin, TX',
        type: 'Full-time',
        experience: '5+ years',
        description: 'Focus on building highly responsive UI components.',
        requirements: ['React expertise', 'Tailwind CSS', 'TypeScript'],
        skills: ['React', 'Next.js', 'TypeScript'],
        projectRole: 'Frontend Lead',
        projectDescription: 'Lead the migration of our legacy dashboard to Next.js.',
        educationalQualifications: 'Bachelor’s degree in CS',
        benefits: ['Unlimited PTO', 'Home Office Stipend'],
        summary: 'Senior role for a UI specialist.',
        postedDate: '2024-06-05',
    },
    {
        id: 'NOWIT-JO-003',
        section: 'uiuxdesigning',
        role: 'UX Designer',
        detailedRole: 'Product Designer (Mobile)',
        location: 'San Francisco, CA',
        type: 'Contract',
        experience: '3+ years',
        description: 'Create intuitive user journeys for our mobile apps.',
        requirements: ['Figma mastery', 'Strong Portfolio', 'User Testing'],
        skills: ['Figma', 'Adobe XD', 'Prototyping'],
        projectRole: 'UX Designer',
        projectDescription: 'Redesigning the onboarding flow.',
        educationalQualifications: 'Degree in Graphic Design',
        benefits: ['Gym Membership', 'Free Lunch'],
        summary: 'Perfect for a creative problem solver.',
        postedDate: '2024-06-10',
    },
    {
        id: 'NOWIT-JO-004',
        section: 'development',
        role: 'Backend Developer',
        detailedRole: 'Node.js Specialist',
        location: 'London, UK',
        type: 'Full-time',
        experience: '4+ years',
        description: 'Scalable API development and database management.',
        requirements: ['Node.js', 'PostgreSQL', 'Redis'],
        skills: ['Node.js', 'Express', 'SQL'],
        projectRole: 'Backend Engineer',
        projectDescription: 'Building a real-time notification system.',
        educationalQualifications: 'B.Tech in CS',
        benefits: ['Private Healthcare', 'Commuter Benefits'],
        summary: 'Deep dive into server-side architecture.',
        postedDate: '2024-06-12',
    },
    {
        id: 'NOWIT-JO-005',
        section: 'qatesting',
        role: 'QA Engineer',
        detailedRole: 'Automation Test Engineer',
        location: 'Remote',
        type: 'Full-time',
        experience: '2+ years',
        description: 'Ensure our products are bug-free and performant.',
        requirements: ['Selenium/Cypress', 'JavaScript', 'Manual testing'],
        skills: ['Cypress', 'Playwright', 'Jest'],
        projectRole: 'Tester',
        projectDescription: 'Building automated regression suites.',
        educationalQualifications: 'Bachelor’s in Engineering',
        benefits: ['Internet Allowance', 'Medical Insurance'],
        summary: 'Guardian of software quality.',
        postedDate: '2024-06-15',
    },
    {
        id: 'NOWIT-JO-006',
        section: 'uiuxdesigning',
        role: 'UI Designer',
        detailedRole: 'Visual Design Specialist',
        location: 'Berlin, Germany',
        type: 'Full-time',
        experience: '2+ years',
        description: 'Crafting beautiful interfaces for web applications.',
        requirements: ['Visual Hierarchy', 'Color Theory', 'Figma'],
        skills: ['Figma', 'Sketch', 'Illustrator'],
        projectRole: 'UI Lead',
        projectDescription: 'Defining the brand design system.',
        educationalQualifications: 'BFA in Design',
        benefits: ['Equity Options', 'Flexible Hours'],
        summary: 'Create the look and feel of our brand.',
        postedDate: '2024-06-18',
    },
    {
        id: 'NOWIT-JO-007',
        section: 'development',
        role: 'Full Stack Developer',
        detailedRole: 'MERN Stack Developer',
        location: 'Chicago, IL',
        type: 'Full-time',
        experience: '3+ years',
        description: 'Work on both frontend and backend features.',
        requirements: ['React', 'Node.js', 'MongoDB'],
        skills: ['JavaScript', 'React', 'Node.js'],
        projectRole: 'Full Stack Engineer',
        projectDescription: 'Developing a customer portal from scratch.',
        educationalQualifications: 'Computer Science degree',
        benefits: ['Paid Travel', 'Health Savings Account'],
        summary: 'End-to-end development opportunity.',
        postedDate: '2024-06-20',
    },
    {
        id: 'NOWIT-JO-008',
        section: 'qatesting',
        role: 'Manual Tester',
        detailedRole: 'Quality Assurance Analyst',
        location: 'Toronto, Canada',
        type: 'Part-time',
        experience: '1+ year',
        description: 'Perform exploratory and regression testing.',
        requirements: ['Bug tracking', 'Analytical thinking', 'Reporting'],
        skills: ['Jira', 'TestRail', 'Documentation'],
        projectRole: 'QA Analyst',
        projectDescription: 'Testing the new fintech mobile app.',
        educationalQualifications: 'Any Bachelor’s degree',
        benefits: ['Flexible Schedule', 'Learning Credits'],
        summary: 'Shape our product reliability.',
        postedDate: '2024-06-22',
    },
    {
        id: 'NOWIT-JO-009',
        section: 'development',
        role: 'Mobile Developer',
        detailedRole: 'React Native Developer',
        location: 'Paris, France',
        type: 'Contract',
        experience: '3+ years',
        description: 'Build cross-platform mobile applications.',
        requirements: ['React Native', 'Mobile UI/UX', 'API integration'],
        skills: ['React Native', 'TypeScript', 'Firebase'],
        projectRole: 'Mobile Lead',
        projectDescription: 'Launching the v2.0 mobile app.',
        educationalQualifications: 'Degree in Software Engineering',
        benefits: ['Creative Freedom', 'Studio Access'],
        summary: 'Build apps that reach millions.',
        postedDate: '2024-06-25',
    },
    {
        id: 'NOWIT-JO-010',
        section: 'uiuxdesigning',
        role: 'Interaction Designer',
        detailedRole: 'Motion Graphics Designer',
        location: 'Seattle, WA',
        type: 'Full-time',
        experience: '4+ years',
        description: 'Focus on how the product feels and reacts to user input.',
        requirements: ['After Effects', 'Lottie', 'UI Animation'],
        skills: ['After Effects', 'Figma', 'Protopie'],
        projectRole: 'Designer',
        projectDescription: 'Enhancing the interactivity of the dashboard.',
        educationalQualifications: 'Design degree',
        benefits: ['Premium Health Plan', 'Retirement Bonus'],
        summary: 'Perfect the user experience through motion.',
        postedDate: '2024-06-28',
    }
];