import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import NowitContextProvider from "@/store/NowitContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-inter',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <NowitContextProvider>
          <Layout> {children} </Layout>
        </NowitContextProvider>
      </body>
    </html>
  );
}
