import { Geist, Geist_Mono, Inter, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import NowitContextProvider from "@/store/NowitContext";
import { Toaster } from 'sonner'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-inter',
});

const ibmPlex = IBM_Plex_Sans({
  subsets: ['latin'],
  weights: ['300', '400', '500', '600', '700'],
  variable: '--font-ibm-plex-sans',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} ${ibmPlex.variable}  antialiased`}
      >
        <NowitContextProvider>
          <Layout> {children} </Layout>
          <Toaster position="bottom-left" closeButton />
        </NowitContextProvider>
      </body>
    </html>
  );
}
